version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.5.6-jessie
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip setuptools
          pip install pylint
      - run: |
          . venv/bin/activate
          pylint tap_closeio --disable missing-docstring,logging-format-interpolation,too-many-locals,too-many-arguments,too-few-public-methods,invalid-name,len-as-ition,bare-except,inconsistent-return-statements,broad-except
